### ISSUE TITLE
Using READDIRPLUS

### ISSUE THREAD

**Issue by roman-himmelreich-sp** [DeCoRawr/NFSClient#2]
Hi,
There are two functions which list folder items: READDIR and READDIRPLUS Basically, READDIR only returns paths, READDIRPLUS returnes all other attributes.
When calling READDIRPLUS, there are two extra paramters that I can't understand how to use:

dircount 
The maximum number of bytes of directory information to be returned. This number does not include the size of the attributes and file handle portions of the result.
maxcount 
The maximum size of the READDIRPLUS3resok structure, in bytes. The size must include all XDR overhead. The server may return fewer than maxcount bytes of data. 

No matter what I try, I can't seem to get it right.
Did anybody ever call this function succesfully?

**Comment by DeCoRawr** [comment]
Hi,

well it's been 2 years from active delevoplent of the client.

Why do you need the READDIRPLUS implementation ?

I rly don't remember what are the correct attributes now.



2015-11-12 17:42 GMT+01:00 roman-himmelreich-sp <notifications@github.com>:

**Comment by roman-himmelreich-sp** [comment]
Hi, 

thank you for your reply.

I need ReadDirPlus because we are building a Crawler for NFS.
Using ReadDir we would need to send a seperate request per item - to find out if its a folder/file and get the other attributes.
ReadDirPlus gets the list of items with the attributes in a single call.

I see there is an implementation for it, but you did not use it in the client.
The problem seems to be in the decoding and reading of the reply of ReadDirPlus. It returns OK and then somewhere during the XDR parsing of FolderEntry it fails.

If you could point me to where I can find the exact structure of the result that FolderEntry is trying to parse, maybe I can get it working.
I've tried comparing the parsing to the native libnfs code, but there they work with structs, the xdrDecoding is different because we need to know the order of the fields, as I understand...

thanks for any help in advance!
Roman.

**Comment by roman-himmelreich-sp** [comment]
Hi,


Eventually I found the problem,

You were missing one Boolean read from the XDR stream

and then the other read attempts were out of sync and everything failed.


READDIRPLUS gives you the contents of a folder with item attributes - in one call.


thanks for the source, it was really helpful!


________________________________

**Comment by DeCoRawr** [comment]
uf i totaly forgot about this. :S

could you tell me where was this boolean missing ?



2015-12-08 18:11 GMT+01:00 roman-himmelreich-sp <notifications@github.com>:

**Comment by roman-himmelreich-sp** [comment]
Sure!
I will send it to you once I'm n front of it...

**Comment by roman-himmelreich-sp** [comment]
Hi,


I made a few changes to make the MainForm work with READDIR_PLUS too

so it doesn't need to issue a seperate request for the attributes of each file


I would like to push the changes to git so you can see them

but I have no permissions

how does this work? is there some way I can publish this for you to see?

**Comment by DeCoRawr** [comment]
I added you as contributor so you can push the changes now.

Thanks for everything.

DeCoRawr

2015-12-27 9:53 GMT+01:00 roman-himmelreich-sp <notifications@github.com>:
