### ISSUE TITLE
NFSclient v 0.6 MSI does not install on Windows 10 (Home)

### ISSUE THREAD

**Issue by sean729** [DeCoRawr/NFSClient#4]
I suspect we can still extract the contents of the MSI and it would work?

DokanLibraryInstaller 0.6.0 Setup
---------------------------
Your OS is not supported. Dokan library supports Windows 2003, Vista, 2008, 2008R2 and 7 for x64.

**Comment by DeCoRawr** [comment]
Yeah if u can extract contents and install newer version of dokan library
0.7.4.

Thanks for reporting. Was still on win 7 when i programed this.

Will update code and version of dokan.

Thanks Dean

V V pet., 24. avg. 2018 ob 19:17 je oseba sean729 <notifications@github.com>
napisala:

**Comment by DeCoRawr** [comment]
Updated the install code, updated binaries. Installs ok on Win 10. Dokany should work ok. Havent got time to test it but now you can  ;)  Post if everything is ok thanks

**Comment by sean729** [comment]
@davidanger might want to also try the FOSS project Windows FSP at http://www.secfs.net/winfsp/ and see the links for the SSH and NFS extensions to Windows Explorer. I had luck connecting to NFS v3 on CentOS7, assuming you have the FW rules proper.

**Comment by davidanger** [comment]
Thanks @DeCoRawr  and @sean729
